### PR TITLE
Enable Errors and stop running if a task fails.

### PR DESCRIPTION
**Pull request by b-hayes**
It's better if the user of the library decides how errors are handled esp if it's mostly running their own code.

### CODE REVIEW

**Review by joshmcrae — COMMENTED** [review]
@b-hayes Can you provide an example of how a user might handle errors from this tool by themselves? It's intended to be called from a shell rather than imported into another PHP script, so letting an exception bubble to the top and crash the program doesn't seem useful other than to provide a detailed stack trace and actual exit code, but both of those things could be achieved more intentionally with a top-level exception handler.

**Comment by b-hayes** [comment]
Yeah, you are right the bin file probably needs to keep the try-catch.

I normally would but I saw it this way:

- this is a developer tool
- the developer's code/commands are imported and run by Tapegun
- if I add a `--debug` option the developer would then have to run another failed deployment and waste 30 minutes to see the problem.

So yeah that's why I also removed it from the shell command.

If you want I can put the try-catch back into the bin file and have it detect a `--debug` option to stop catching it.

And then our elvanto script that wraps it can just always run with the debug option.

**Comment by joshmcrae** [comment]
@b-hayes An extra flag to add verbosity is a good idea. That could expand beyond the existing message that is output to include the stack trace.

I'd have the `exit` return a status code of 1 as well to make this more scriptable.

**Comment by b-hayes** [comment]
The ugly thing about it is having to handle options in the bin file when we already use a console library. But unfortunately, the command can't disable Symphony console's built-in error handler it has to be done from outside 🤦🏻‍♂️

**Review by joshmcrae — APPROVED** [review]

**Comment by b-hayes** [comment]
@joshmcrae we good to merge this?

**Pull request merged**
